apiVersion: v1
kind: Secret
metadata:
  labels:
    gateway.open-cluster-management.io/cluster-credential-type: X509Certificate
    gateway.open-cluster-management.io/cluster-endpoint-type: Const
  name: foo1
  namespace: open-cluster-management-credentials
type: Opaque
data:
  ca.crt: <...>
  tls.crt: <...>
  tls.key: <...>
  endpoint: "https://127.0.0.1:6443" # Optional upon ClusterProxy endpoint type
