apiVersion: v1
data:
  ca.crt: <...>
  namespace: a3ViZS1zeXN0ZW0=
  token: <...>
  # no endpoint are required
kind: Secret
metadata:
  labels:
    gateway.open-cluster-management.io/cluster-credential-type: ServiceAccountToken
    gateway.open-cluster-management.io/cluster-endpoint-type: Const
  name: foo1
  namespace: open-cluster-management-credentials
type: Opaque