# Image of the cluster-gateway instances
image: ghcr.io/kluster-manager/cluster-gateway

tag: latest

# Number of replicas
replicas: 1

clusterProxy:
  enabled: false
  endpoint:
    host: proxy-entrypoint.open-cluster-management-cluster-proxy
    port: 8090

featureGate:
  healthiness: false
